version: '3'

services:
  db:
    image: postgres
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: mypassword
  web:
    image: jimboeri/web-monitor
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  script:
    image: jimboeri/script-monitor
    build:
      context: .
      dockerfile: script-dockerfile
    environment:
      MQTT_CLIENT_ID: mqtt_monitor_test
    command: python mqtt-monitor.py
    volumes:
      - .:/code
    restart: always
    depends_on:
      - db
volumes:
  dbdata: